spring:
  application:
    name: Eventos

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/eventos_db?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port: 8080
